### ISSUE TITLE
Data engineering learning path's index is broken

### ISSUE THREAD

**Issue by gautamkrishnar** [tinkerhub-org/TinkerHub-Learning-Paths#32]
**Learning Path Name:** Data engineering
https://tinkerhub.org/learn/data-engineering/

#### Suggested changes
We have to fix the data engineering index similar to the stuff we did for #30, check out the PR #31

**Comment by nikiljos** [comment]
https://github.com/tinkerhub-org/TinkerHub-Learning-Paths/pull/33 Pls check this PR wether it works
