### ISSUE TITLE
Improve the app header

### ISSUE THREAD

**Issue by gautamkrishnar** [tinkerhub-org/TinkerHub-Learning-Paths#40]
Following are the list of suggestions to improve the crrent header of https://tinkerhub.org/learn

#### Desktop
<img src='https://user-images.githubusercontent.com/8397274/117845766-786e3f00-b29e-11eb-8973-9609cef8b6eb.png' width='600px'>

#### Mobile
<img src='https://user-images.githubusercontent.com/8397274/117845837-8623c480-b29e-11eb-9b00-18a4261b8a86.png' width='300px'>

## Suggestions
* Make the search bar visible in all screen-sizes including mobile
* The 'add new path' link is very large we should use a '+' icon instead of it

Source: @LunaticHacker's coment on https://github.com/tinkerhub-org/TinkerHub-Learning-Paths/pull/38#pullrequestreview-656303407

## ToDo
- [ ] Design a wireframe - Add as a comment to this issue
- [ ] Implement the design - Open a PR once the design is approved

**Comment by adarshajit** [comment]
Hello there.....
I'm attaching the link to the Figma file herewith. Just an attempt. Do let me know what you think! Cheers.
https://www.figma.com/file/XsN5TxDG4gDIbFMm6bwYc0/TinkerHub-Navbar?node-id=0%3A1

**Comment by gautamkrishnar** [comment]
Looks great @adarshajit Great job, Can you please make the search box square instead of rounded borders to match the existing UI.

![Screenshot 2021-05-12 at 12 04 02 PM](https://user-images.githubusercontent.com/8397274/117929307-44d0fa80-b31a-11eb-8129-d27cda460c82.png)

**Comment by adarshajit** [comment]
Hey.....As per your feedback, I changed it. Take a look!

**Comment by gautamkrishnar** [comment]
Looks great. Attaching it here.

![Screenshot 2021-05-12 at 12 40 36 PM](https://user-images.githubusercontent.com/8397274/117933721-7e583480-b31f-11eb-95dc-0c67caea0876.png)

**Comment by LunaticHacker** [comment]
@adarshajit  are you working on the implementation? if not, i can work on it.

**Comment by gautamkrishnar** [comment]
@LunaticHacker you can work on it, @adarshajit was just designing the wireframe.

**Comment by adarshajit** [comment]
Actually, I was trying to implement it. I was busy with other stuff. Is there a deadline lol.

**Comment by gautamkrishnar** [comment]
@adarshajit nope, but it would be better if we can get it done earlier. Since you are busy lets have @LunaticHacker work on it. I said you are not working on it because i didnt see you forking the repository.
